title: ken-guru / lab
description: Lab experiments in AI-assisted development
url: "https://www.paulsennet.no"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
