title: ken-guru / lab
description: Lab experiments in AI-assisted development
url: "https://www.paulsennet.no"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
cloudflare_analytics_token: "a319a53ebf89412687c4d3d1f01b9fa1"
